### ISSUE TITLE
originInfo should be repeatable

### ISSUE THREAD

**Issue by mdemers** [FLVC/islandoratheme#29]
```
<originInfo>
  <place>
    <placeTerm type="text">Here</placeTerm>
  </place>
  <publisher>Bureau of Geology</publisher>
</originInfo>
<originInfo>
  <place>
    <placeTerm type="text">There</placeTerm>
  </place>
  <publisher>penguin</publisher>
  <dateIssued>1942</dateIssued>
</originInfo>
```
Publication information from both originInfo tags should appear. Only the top will currently display.

**Comment by Favenzio** [comment]
Mike,

Could you add a record in Dev with this problem so I can fix and test?

Thanks.

**Comment by mdemers** [comment]
Sure. It looks like this record has two originInfo elements: http://islandora7d.fcla.edu/islandora/object/islandora%3A4562#

**Comment by Favenzio** [comment]
Looking at your sample record, the second originInfo gets added at the end of the MODS file. How would you like the second originInfo to display? Should it add the information to the the first Origin Info? or should it create its own display at the bottom? Right now originInfo is not displayed as a group, we just take the child elements and display them individually. For example, in your sample record there are 3 placeTerms for the first originInfo (only two display due to logic that suppresses type='code') and 1 for the second one. Should the display add a third line to the 'Place of Publication' at the top, or should it create another 'Place of Publication' at the bottom?

**Comment by mdemers** [comment]
Given that it's in a separate top-level element I guess it should create its own label. It won't look as good but it'll give a more accurate representation of what is in the MODS.

**Comment by Favenzio** [comment]
Mike,

I have made changes to allow for multiple origin info elements. Please test and let me know if it works as you would expect.

**Comment by mdemers** [comment]
Looks good to me.

**Comment by Favenzio** [comment]
Patch has been applied to production.
